// <auto-generated />
namespace GarageII_TheParking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_added_name_to_garage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_added_name_to_garage));
        
        string IMigrationMetadata.Id
        {
            get { return "201605121202045_Added_added_name_to_garage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
