// <auto-generated />
namespace GarageII_TheParking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LooserGarageConnectionII : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LooserGarageConnectionII));
        
        string IMigrationMetadata.Id
        {
            get { return "201605170706499_LooserGarageConnectionII"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
